# Generated by Django 6.0.1 on 2026-04-15 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "course"], name="materials_s_user_id_3ebfb2_idx"
            ),
        ),
    ]
