# Generated by Django 6.0.1 on 2026-04-15 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
